
/**
 * Extra parameters used by Drunken Octopus
 */
//#define SOURCE_CODE_URL
//#define SHORT_BUILD_VERSION
//#define TOOLHEAD_NAME
//#define TOOLHEAD_TYPE
//#define WIPE_SEQUENCE_COMMANDS
//#define AXIS_LEVELING_COMMANDS
//#define BED_LEVELING_COMMANDS
//#define MANUAL_BED_LEVELING_COMMANDS
//#define AO_EXP1_DEPRECATED_PINMAP
//#define DISABLE_DUE_SD_MMC
//#define ARCHIM2_SPI_FLASH_EEPROM_BACKUP_SIZE
//#define END_G29_ON_BACK_LEFT_CORNER
//#define G26_IN_START_GCODE_WORKAROUND
//#define USB_DEVICE_VENDOR_ID
//#define USB_DEVICE_PRODUCT_ID
//#define USB_DEVICE_PRODUCT_NAME
//#define TOUCH_UI_SYNDAVER_LEVEL
//#define TOUCH_UI_SYNDAVER_LEVELUP
//#define TOUCH_UI_NO_BOOTSCREEN
//#define TOUCH_UI_ROYAL_THEME
//#define TOUCH_UI_VERSION
//#define TOUCH_UI_FILAMENT_RUNOUT_WORKAROUNDS
//#define CURA_LE_RUNOUT_HANDLING_WORKAROUND
//#define FIL_RUNOUT_PIN
//#define SERVO0_PIN
//#define ACTION_ON_FILAMENT_RUNOUT
//#define SWAP_EXTRUDER_FANS
//#define SWAP_E0_AND_E1
//#define Z_STOP_PIN
//#define Z_MAX_PIN
//#define NO_MOTION_BEFORE_HOMING_WORKAROUND
//#define NO_TIME_AFTER_SD_PRINT
//#define EMI_MITIGATION
//#define Z_MIN_PROBE_REPEATABILITY_TEST
//#define Z2_PRESENCE_CHECK
//#define USE_ELECTROMAGNETIC_BRAKE
//#define ELECTROMAGNETIC_BRAKE_PIN
//#define UBL_HILBERT_CURVE
//#define M997_ARCHIM_BOOTLOADER
//#define START_PRINT_TIMER_ON_G26
//#define MOVE_TO_Z_MIN_COMMANDS
//#define MOVE_TO_Z_MAX_COMMANDS
//#define MOVE_TO_MAINT_COMMANDS
//#define MOVE_TO_FIL_CHG_COMMANDS
